* Semantic Zoom

https://github.com/user-attachments/assets/284a77ca-1e07-4c55-bd82-178733eb4034

A github repository curating semantic zoom interaction pattern. Semantic zoom is an interaction technique for making the information density in a UI artefact coarser/finer. The representation / functionality afforded at a particular level of detail aligns with the user intent. They have started to gain prominence with AIs enabling multi-level text summaries.

** [[https://alexanderobenauer.com/labnotes/038/][Alexander Obenaeur / Semantic Zoom Labnote]]

https://github.com/user-attachments/assets/9e358fc4-e99e-4627-8101-25461db5e058

Alexander Obenauer has spent a lot of time thinking about how semantic zoom might fit as an operating system primitive.

** [[https://x.com/OrionReedOne/status/1790263523857019227][Orion Reed]]

https://github.com/user-attachments/assets/4451a5e8-07d6-4fe8-b8b7-b0d368ee5efd

Clever example where the content shrinks to graph nodes on zooming out.

** [[https://wattenberger.com/thoughts/fish-eye][Amelia Wattenberger / Fish Eye]]
Amelia seems to have kicked off a flurry of activity with her fish eye experiments.

https://github.com/user-attachments/assets/0e0201ab-1165-4f03-8823-e558faa3ebc3

Some of the works inspired from her posts:

- [[https://x.com/0xRaduan/status/1936347428804043048][Raduan Al-Shedivat’s Reading Digest example]]

https://github.com/user-attachments/assets/b7eb4ab3-018d-4e97-857a-3abeeb3c1f1b

- [[https://x.com/kothiyalsen/status/1775799665801240686][Siddharth Kothiyal’s mobile UI]]
 
https://github.com/user-attachments/assets/bd2ac114-a6b2-4949-99d3-64c9f16673fb

https://github.com/user-attachments/assets/b83202fd-668f-48fa-889c-5b1882a419a4

** [[https://x.com/tldraw/status/1805187091438895190][Tldraw visual summaries]]
https://github.com/user-attachments/assets/f72021a6-e3b9-499c-a65b-75126cac82f3

Summarizing images by visual themes.

** [[https://x.com/neilsonks/status/1744805355182608680][Neilson’s Experiments]]
Fascinating example of elaborating/summarizing text by pulling apart / pinching.

https://github.com/user-attachments/assets/85772336-b16f-4261-89ad-f55902d81ba3

https://github.com/user-attachments/assets/19ecb155-30e2-4f14-bfa7-b77c9e952b44

** [[https://x.com/tommyghung/status/1791252809440178627][Tommy Hung’s node based semantic zoom]]

https://github.com/user-attachments/assets/bd350a31-f286-4514-9abd-1e3ccc8ba389

https://github.com/user-attachments/assets/c7afe754-b13c-4f4f-8234-f1e2741c4645

** USCD HCI Lab works

USCD HCI labs is producing some very interesting work in HCI ∩ AI: https://hci.ucsd.edu/ai


*** [[https://x.com/HaijunXia/status/1646919380704559104][Sensescape]]
Made by [[https://x.com/HaijunXia][Haijun Xia]], [[https://x.com/sangho_suh][Sangho Suh]], [[https://x.com/bryandhmin][Bryan Min]], and [[https://x.com/SrishtiPalani][Srishti Palani]]

https://github.com/user-attachments/assets/343aeab1-da9c-4aef-bf83-aedc938c492d

*** [[https://x.com/HaijunXia/status/1646917869115166720][Graphologue]]
Made by [[https://x.com/peilingjiang][Peiling Jiang]], [[https://x.com/juderayan_][Jude Rayan]], and [[https://x.com/stevendow][Steven Dow]]
https://github.com/user-attachments/assets/10447d52-1ea6-4299-9458-4af3b6af6535

** [[https://x.com/max__drake/status/1643594487971676160][Make Drake]]
Interesting example with progressive unfolding of content.
https://github.com/user-attachments/assets/596e3a82-3fbf-4eb7-b317-6d1461cd15ad

I mulled on an idea of extending this to blending prose here: https://x.com/prathyvsh/status/1949349549535035523

* Historical precursors

** [[https://en.wikipedia.org/wiki/StretchText][StretchText]]
One of the first examples by Ted Nelson on progressively revealing content

** [[https://www.telescopictext.org/][TelescopicText]]

** [[https://skorokithakis.github.io/expounder/][Expounder]]

** ZUI

*** [[https://www.youtube.com/watch?v=BlIRYTuSv0Q][Pad++]]
*** [[https://sourceforge.net/projects/eaglemode/][EagleMode]]

* Interesting adjacent experiments

** Twine: https://twinery.org/
Non-linear interactive fiction

** Adjacent articles I haven’t read but looks interesting
https://aeon.co/essays/when-ai-summaries-replace-hyperlinks-thought-itself-is-flattened




